config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'

  devise_for :users
  root to: "pages#home"
  resources :locations
  resources :sellers, :only => :index
  resources :listings do
    resources :orders
  end
end

app/models/buyer.rb
class Buyer < User
  has_many :orders
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :location
  belongs_to :seller
  has_one :order
  

  # Validations for a listing to be created
  validates :title, :location_id, :address, :postcode, :price, :avatar, :presence => true
  validates :price, numericality: { greater_than: 0 }  
end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :name  
  after_validation :geocode 

  has_many :listings      
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :address,:city,:postcode, :presence => true
  belongs_to :buyer
  belongs_to :seller
  belongs_to :listing
end

app/models/seller.rb
class Seller < User
  has_many :listings, dependent: :destroy
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :type


  # User account details
  attr_accessor :account_number
  attr_accessor :account_routing
  attr_accessor :account_country
  attr_accessor :stripe_token


  before_create do

    Stripe.api_key = ENV['STRIPE_API_KEY']

    # Get the bank account details submitted by the form
    token_id = self.stripe_token

    # Create a Recipient
    recipient = Stripe::Recipient.create(
      :name => "#{self.first_name} #{self.last_name}",
      :type => "individual",
      :email => self.email,
      :bank_account => token_id
    )

    self.recipient_id = recipient.id

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name,
      :last_name,:email,:type,:password,:password_confirmation,
      :account_number,:account_routing,:account_country,:stripe_token,:recipient_id)}
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, :only => :index

  def index
    @listings = Listing.all
  end

  def show
    @listing = Listing.find(params[:id])
    if current_user.id != @listing.seller.id && current_user.type != "Buyer"
      redirect_to root_url, :alert => "Please create a buyer account to view this page"
    end
  end

  def create
    @listing = Listing.new(allowed_params)
    @listing.seller_id = current_user.id

    if @listing.save
      redirect_to sellers_path, :notice => "Record Saved"
    else
      redirect_to sellers_path, :alert => @listing.errors.full_messages.to_sentence
    end  
  end

  private
  def allowed_params
    params.require(:listing).permit(:title,:description,:address,:postcode,:price,:location_id,:seller_id,:avatar)
  end
  #Checking if current user is of type buyer
  def check_user
    if current_user.type != "Buyer" 
      redirect_to root_url, :alert => "Please create a buyer account to view this page"
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  def index
    @locations = Location.paginate(:page => params[:page])
    @locations.sort_by{|location| location.name.downcase}
  end

  def show
    @location = Location.find(params[:id])
    @client = GooglePlaces::Client.new(ENV["GOOGLE_API_KEY"])
    @parkings = @client.spots(@location.latitude, @location.longitude, :types => 'parking',
     :radius => 2000,:exclude => ['cafe','restaurant','lodging','food'])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, :only => [:new, :create]

  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  def create
  
    @listing = Listing.find(params[:listing_id])
    @order = Order.new(allowed_params)
    @order.listing_id = @listing.id
    @order.seller_id = @listing.seller_id
    @order.buyer_id = current_user.id

    # Charging credit card
    Stripe.api_key = ENV['STRIPE_API_KEY']

    # Get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create the charge on Stripe's servers - this will charge the user's card
    begin
    charge = Stripe::Charge.create(
      :amount => (@listing.price * 100).floor, # amount in cents, again
      :currency => "usd",
      :card => token,
      :description => @listing.title
    )

    rescue Stripe::CardError => e
      flash[:alert => e.message]
    end

    Stripe::Transfer.create(
      :amount => charge.amount,
      :currency => charge.currency,
      :recipient => @listing.seller.recipient_id,
      :description => "#{@listing.title} payment"
    )
 
    if @order.save
      @listing.destroy
      redirect_to root_path, :notice => "Transaction completed"
    else
      redirect_to new_listing_order_path, :alert => @order.errors.full_messages.to_sentence
    end

  end

  private
  def allowed_params
    params.require(:order).permit(:address,:city,:postcode,:listing_id,:seller_id,:buyer_id)
  end
   #Checking if current user is of type buyer
  def check_user
    if current_user.type != "Buyer"
      redirect_to root_url, :alert => "Please create a buyer account to view this page"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user
  def index
    @listing = Listing.new
    @seller = current_user
  end
  
  #Checking if current user is of type seller
  private
  def check_user
    if current_user.type != "Seller"
      redirect_to root_url, :alert => "Please create a seller's account to view this page"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sign_in.html.haml
= form_for(resource, as: resource_name, url: session_path(resource_name),html: {:class => "navbar-form navbar-right", :id => "sign_in"}) do |f| 

  .form-group
    = f.email_field :email, autofocus: true, :class => "form-control", :placeholder => "Email" 

  .form-group
    = f.password_field :password, autocomplete: "off",:class => "form-control", :placeholder => "Password" 

  = f.submit "Sign in", :class => "btn btn-success",:type => "submit" 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Parking Finder
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 

    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}" 
  
    = javascript_include_tag "https://js.stripe.com/v2/" 

    = javascript_tag "Stripe.setPublishableKey('#{ENV['STRIPE_PUBLIC_KEY']}')" 
   
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 

    = csrf_meta_tags 

  %body

    .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button{:type => "button", :class =>"navbar-toggle", :"data-toggle" => "collapse", :"data-target" => ".navbar-collapse"}
            %span.sr-only
              Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar

          = link_to  "Parking Finder", root_path, :class => "navbar-brand" 

        .navbar-collapse.collapse

          - if user_signed_in? 
            %ul.nav.navbar-nav
              %li{:class => " = 'active' if params[:controller] == 'pages' "}
                = link_to "Home",root_path 
              %li{:class => " = 'active' if params[:controller] == 'listings' "}
                = link_to "Buy a Parking",listings_path 
              %li{:class => " = 'active' if params[:controller] == 'locations' "}
                = link_to "Find a Parking",locations_path 
   
              - if current_user.type == "Seller" 
                %li{:class => " = 'active' if params[:controller] == 'sellers' "}
                  = link_to "Seller account",sellers_path 
  

            = button_to 'Logout', destroy_user_session_path, :method => :delete, :type => "button", :class => "btn btn-default navbar-btn btn-success navbar-right"    

            %p.navbar-text.navbar-right.sign-in Signed in as "#{current_user.first_name} #{current_user.last_name}"   
            
          - else 
            
            = render "layouts/sign_in" 
   


    - if flash[:alert] 
      #general-alert.alert.alert-danger{:role => "alert"} 
        = flash[:alert] 

    - if flash[:notice]   
      #general-alert.alert.alert-success{:role => "alert"}
        = flash[:notice]

    = yield 



    .container.text-left
      %footer
        %p &copy; We Got Coders 2014

app/views/listings/index.html.haml
.container.main
  .row
    .col-md-12
      %h1
        Parkings for sale

  .row
    - @listings.each do |listing| 
      .col-md-4
        .parking.text-center
          = image_tag listing.avatar.url,:class => "img-responsive shadow" 
          .inner
            %h4= "#{listing.title} ( #{listing.location.name} )"
            %p= "Price #{number_to_currency(listing.price ,unit: "£",:precision => (listing.price.round == listing.price) ? 0 : 2)}" 
            %p.view
              = link_to "View listing &raquo;".html_safe, listing_path(listing), :class => "btn btn-info", :role => "button" 

app/views/listings/show.html.haml
.container.main
  .row
    .col-md-12
      %h1= @listing.title 

  .row
    .col-md-6
      = image_tag @listing.avatar.url , :class => "img-responsive show-parking shadow" 

    .col-md-6
      %p
        %b Area: #{@listing.location.name}
      %p
        %b Sold by: #{@listing.seller.first_name} #{@listing.seller.last_name}
      %p
        %b Address: #{@listing.address} 
      %p
        %b Postcode: #{@listing.postcode} 
      %p
        %b Description: #{@listing.description} 
      %p
        %b Price: #{number_to_currency(@listing.price ,unit: "£",:precision => (@listing.price.round == @listing.price) ? 0 : 2)}
      %p= link_to "Buy Now", new_listing_order_path(@listing), :class => "btn btn-success", :type => "button"
  

app/views/locations/index.html.haml
.container.main
  .row
    .col-md-12
      %h1
        Parking locations

  .row
    .col-md-12.text-center 
      %p
        = will_paginate 
      .all-locations
        - @locations.each do |location| 

          =link_to location.name, location_path(location),:class => "location"
          
        .clearfix

app/views/locations/show.html.haml
.container.main
  .row
    .col-md-12
      %h1
        = @location.name 
        
  .row
    .col-md-12
      = content_tag :div, id: "map-canvas", data: {latitude: @location.latitude, longitude: @location.longitude, parkings: @parkings} do end

  .row
    .col-md-6
      %h2
        Route 
      #directions-panel

app/views/orders/new.html.haml
.container.main
  .row
    .col-md-12
      %h1
        Customer details
  .row
    .col-md-6
      = form_for [@listing,@order], url:{action: "create"}  do |f| 
        .alert.alert-danger.payment-errors { role="alert" }

        .form-group
          = f.label :address 
          = f.text_field :address, :class => "form-control" 

        .form-group
          = f.label :city 
          = f.text_field :city, :class => "form-control" 
        .form-group
          = f.label :postcode 
          = f.text_field :postcode, :class => "form-control"  
        .form-group
          = label_tag :credit_card,"Credit Card No." 
          = text_field_tag :credit_card, nil, :class => "form-control", :data => {:stripe => "number"}, :name => nil 
        .form-group
          = label_tag :cvc,"CVC"
          = text_field_tag :cvc, nil, :class => "form-control",:data => {:stripe => "cvc"}, :name => nil   

        .form-group
          = label_tag :exp_date, "Card Expiration"
          = select_month nil, {add_month_numbers_true: true},{name: nil, id: "card_month",:data => {:stripe => "exp-month"}}
          = select_year nil, {start_year: Date.today.year, end_year: Date.today.year + 3},{name: nil, id: "card_year",:data => {:stripe => "exp-year"}} 
   
        .form-group
          = f.submit "Complete order",:class =>"btn btn-success pull-right"

     

app/views/pages/home.html.haml
.jumbotron
  .container.banner-info
    %h1.text-center
      Parking Finder
    %p.text-center
      Whether you want to find a parking space to rent or you want to buy or sell the property itself, Parking finder is here to help you!
    %p.text-center
      = link_to "Register &raquo".html_safe, new_user_registration_path, :class => "btn btn-primary btn-lg",
    :role => "button" 

.container
  .row
    .col-md-6
      %h2
        Buy a parking space
      %p
        Parking properties are available for sale within the area of London.
      %p
        = link_to "View listings &raquo;".html_safe, listings_path, :class => "btn btn-default", :role => "button" 
    .col-md-6
      %h2
        Find a parking space
      %p
        Find a parking space in London with our unique navigation system.
      %p
        = link_to "View areas &raquo;".html_safe, locations_path, :class => "btn btn-default", :role => "button" 
  %hr

app/views/sellers/index.html.haml
.container.main
  .row
    .col-md-12
      %h1
        Seller profile page

  .row
    .col-md-6
      .h3
        Add new listing
      = form_for @listing, url: listings_path do |f| 
        .form-group
          = f.label :title 
          = f.text_field :title,:class => "form-control" 
        .form-group
          = f.label :location 
          = f.select(:location_id,Location.order('name ASC').collect { |location| [location.name, location.id] },{},{:class => "form-control"})
        .form-group
          = f.label :address 
          = f.text_field :address, :class => "form-control" 
        .form-group
        = f.label :postcode 
        = f.text_field :postcode, :class => "form-control" 
        .form-group
          = f.label :description   
          = f.text_area :description, size: "60x12",:class => "form-control" 
        .form-group
          = f.label :avatar, "Image"   
          = f.file_field :avatar , accept: 'image/png,image/gif,image/jpeg',:class => "form-control"
        .form-group
          = f.label :price 
          = f.text_field :price, :class => "form-control" 
        .form-group
          = f.submit "Add new",:class =>"btn btn-default" 
 

    .col-md-6
      %h3
        Current Listings
      - @seller.listings.each do |listing| 
        .listing
          = link_to image_tag(listing.avatar.url , :class => "listing-profile-img"),listing 